---
# tasks file for docker role

- name: Remove old docker packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    update_cache: true
    state: absent
  vars:
    packages:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc

- name: Install packages to allow HTTPS installation
  ansible.builtin.apt:
    name: "{{ packages }}"
    update_cache: true
    state: present
  vars:
    packages:
      - ca-certificates
      - curl

- name: Ensure keyrings directory is created
  ansible.builtin.file:
    path: "{{ apt_keyrings_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Download Docker GPG key.
  ansible.builtin.get_url:
    url: "{{ docker_apt_gpg_key_url }}"
    dest: "{{ docker_apt_gpg_key }}"
    mode: '0644'
    force: true

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repository }}"

- name: Install Docker Packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    update_cache: true
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Ensure /etc/docker/ directory exists.
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: 0755
  when: docker_daemon_options.keys() | length > 0

- name: Configure Docker daemon options.
  ansible.builtin.copy:
    content: "{{ docker_daemon_options | to_nice_json }}"
    dest: /etc/docker/daemon.json
    mode: 0644
  when: docker_daemon_options.keys() | length > 0
  notify: restart docker

- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add users to docker groups
  ansible.builtin.user:
    name: "{{ item }}"
    groups:
      - docker
    append: true
    state: present
    createhome: true
  with_items: "{{ docker_users }}"

- name: Ensure docker and contained service are enabled
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - docker
    - containerd

- name: Ensure handlers are notified now.
  ansible.builtin.meta: flush_handlers
